name: Update the Resume

on: push

jobs:
  generate_cv_job:
    runs-on: ubuntu-latest
    name: A job to generate CV pdf on push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run CV generation
        uses: ./ 

      - name: Set Git user
        run: git config --local user.email "action@github.com"
      
      - name: Add and commit changes
        run: |
          git add .
          git commit -m "Update resume.pdf via GitHub Actions"
      
      - name: Push changes
        run: |
          git push origin HEAD:patch-1
